-- Código por - Joaquín Saldarriaga
-- Inserción de productos para la tabla Products
-- NOTA: category_id debe corresponder al ID de la categoría en la tabla Categories
INSERT INTO Products (product_id, product_name, product_description, product_price, category_id, is_in_stock, created_at, updated_at)
VALUES
  (1, 'Cable USB-B', 'Experience seamless connectivity with our premium Cable USB-B! Perfect for printers, audio interfaces, and countless other devices, this cable ensures your data transfers are fast and reliable every time. Built to last, its flexible yet durable design stands up to daily use—whether at home, in the office, or on the go. Say goodbye to tangled cords and connection issues, and enjoy peace of mind knowing your devices are always ready to perform. Upgrade your tech setup with a cable trusted by professionals and enthusiasts alike!', 109.99, 1, TRUE, NOW(), NOW()),
  (2, 'Wireless Desk Charging', 'Cut the cord and embrace the future with our Wireless Desk Charging station! Effortlessly power up your Qi-enabled devices—just place them on the pad and watch the magic happen, no cables required. Its sleek, minimalist design fits perfectly on any desk or nightstand, keeping your workspace organized and clutter-free. Engineered for safety, it protects your devices from overheating and overcharging, so you can charge with confidence. Stay powered, stay productive, and enjoy the convenience of wireless charging every day.', 149.99, 1, TRUE, NOW(), NOW()),
  (3, 'Smartwatch Samsung Galaxy Fit 3', 'Take charge of your health and stay connected with the Samsung Galaxy Fit 3 Smartwatch! Track your heart rate, monitor your sleep, and count every step with precision—all from your wrist. Receive notifications, control your music, and keep up with your busy life without missing a beat. Designed for comfort and style, it’s lightweight, water-resistant, and ready for any adventure. Empower your fitness journey and enjoy smart features that make every day easier and more inspiring.', 229.99, 1, TRUE, NOW(), NOW()),
  (4, 'Vintage Bluetooth Retro Vinyl Turntable', 'Rediscover the magic of vinyl with our Vintage Bluetooth Retro Vinyl Turntable! Enjoy the warm, authentic sound of your favorite records, or stream music wirelessly from your phone with built-in Bluetooth. Classic retro design meets modern technology, featuring integrated speakers and easy-to-use controls. Perfect for music lovers, collectors, and anyone who appreciates timeless style and rich audio. Bring nostalgia and innovation together—make every listening session an experience to remember.', 2999.49, 1, TRUE, NOW(), NOW()),
  (5, 'Nokia 2660 Flip Phone Zero Distractions', 'Step back to simplicity with the Nokia 2660 Flip Phone—designed for those who value connection without distraction! Enjoy crystal-clear calls, long battery life, and a classic flip design that fits comfortably in your hand or pocket. Perfect for staying in touch with loved ones, focusing on what matters, and escaping the noise of modern smartphones. Reliable, durable, and refreshingly easy to use, it’s the ideal choice for minimalists and anyone seeking a digital detox. Rediscover the joy of communication—pure, simple, and distraction-free.', 639.19, 1, TRUE, NOW(), NOW()),
  (6, 'Galaxy *Ring of Power*', 'Pre-order the revolutionary Galaxy Ring of Power and wear the future on your finger! This stylish smart ring offers advanced health tracking, smart notifications, and seamless connectivity—all in a sleek, comfortable design. Monitor your heart rate, sleep, and activity discreetly, while staying connected to calls, messages, and reminders. Crafted for elegance and engineered for performance, it''s perfect for tech enthusiasts and trendsetters alike. Be among the first to experience the next evolution in wearable technology—reserve your Galaxy Ring of Power today!', 4209.99, 1, TRUE, NOW(), NOW()),
  (7, 'Waymo Ride Gift Card!', 'Unlock the future of transportation with a Waymo Rides gift card! Imagine gifting the freedom of safe, convenient, and autonomous rides to your loved ones. Whether it''s for daily commutes, exploring the city, or getting to appointments - a Waymo gift card offers a unique and forward-thinking way to travel. Make your gift truly personal by choosing the exact amount you want to load onto the Waymo Rides gift card. Simply enter your desired value in the field below. Waymo vehicles are framed & designed with passenger comfort and safety in mind!', 399.99, 1, TRUE, NOW(), NOW());
-- Agrega más productos siguiendo el mismo formato, ajustando category_id según corresponda.
