-- Insert all 190 products from productDetails
-- Category mapping:
-- 1: Technology
-- 2: Office & writing
-- 3: Shirts
-- 4: Household
-- 5: Movies & TV
-- 6: Pet supplies
-- 7: Sports
-- 8: Books

INSERT INTO Products (product_id, product_name, product_description, product_price, category_id, is_in_stock, created_at, updated_at) VALUES
(1, 'Cable USB-B', 'Experience seamless connectivity with our premium Cable USB-B! Perfect for printers, audio interfaces, and countless other devices, this cable ensures your data transfers are fast and reliable every time. Built to last, its flexible yet durable design stands up to daily use—whether at home, in the office, or on the go. Say goodbye to tangled cords and connection issues, and enjoy peace of mind knowing your devices are always ready to perform. Upgrade your tech setup with a cable trusted by professionals and enthusiasts alike!', 109.99, 1, TRUE, NOW(), NOW()),
(2, 'Wireless Desk Charging', 'Cut the cord and embrace the future with our Wireless Desk Charging station! Effortlessly power up your Qi-enabled devices—just place them on the pad and watch the magic happen, no cables required. Its sleek, minimalist design fits perfectly on any desk or nightstand, keeping your workspace organized and clutter-free. Engineered for safety, it protects your devices from overheating and overcharging, so you can charge with confidence. Stay powered, stay productive, and enjoy the convenience of wireless charging every day.', 149.99, 1, TRUE, NOW(), NOW()),
(3, 'Smartwatch Samsung Galaxy Fit 3', 'Take charge of your health and stay connected with the Samsung Galaxy Fit 3 Smartwatch! Track your heart rate, monitor your sleep, and count every step with precision—all from your wrist. Receive notifications, control your music, and keep up with your busy life without missing a beat. Designed for comfort and style, it’s lightweight, water-resistant, and ready for any adventure. Empower your fitness journey and enjoy smart features that make every day easier and more inspiring.', 229.99, 1, TRUE, NOW(), NOW()),
(4, 'Vintage Bluetooth Retro Vinyl Turntable', 'Rediscover the magic of vinyl with our Vintage Bluetooth Retro Vinyl Turntable! Enjoy the warm, authentic sound of your favorite records, or stream music wirelessly from your phone with built-in Bluetooth. Classic retro design meets modern technology, featuring integrated speakers and easy-to-use controls. Perfect for music lovers, collectors, and anyone who appreciates timeless style and rich audio. Bring nostalgia and innovation together—make every listening session an experience to remember.', 2999.49, 1, TRUE, NOW(), NOW()),
(5, 'Nokia 2660 Flip Phone Zero Distractions', 'Step back to simplicity with the Nokia 2660 Flip Phone—designed for those who value connection without distraction! Enjoy crystal-clear calls, long battery life, and a classic flip design that fits comfortably in your hand or pocket. Perfect for staying in touch with loved ones, focusing on what matters, and escaping the noise of modern smartphones. Reliable, durable, and refreshingly easy to use, it’s the ideal choice for minimalists and anyone seeking a digital detox. Rediscover the joy of communication—pure, simple, and distraction-free.', 639.19, 1, TRUE, NOW(), NOW()),
(6, 'Galaxy *Ring of Power*', 'Pre-order the revolutionary Galaxy Ring of Power and wear the future on your finger! This stylish smart ring offers advanced health tracking, smart notifications, and seamless connectivity—all in a sleek, comfortable design. Monitor your heart rate, sleep, and activity discreetly, while staying connected to calls, messages, and reminders. Crafted for elegance and engineered for performance, it''s perfect for tech enthusiasts and trendsetters alike. Be among the first to experience the next evolution in wearable technology—reserve your Galaxy Ring of Power today!', 4209.99, 1, TRUE, NOW(), NOW()),
(7, 'Waymo Ride Gift Card!', 'Unlock the future of transportation with a Waymo Rides gift card! Imagine gifting the freedom of safe, convenient, and autonomous rides to your loved ones. Whether it''s for daily commutes, exploring the city, or getting to appointments - a Waymo gift card offers a unique and forward-thinking way to travel. Make your gift truly personal by choosing the exact amount you want to load onto the Waymo Rides gift card. Simply enter your desired value in the field below. Waymo vehicles are framed & designed with passenger comfort and safety in mind!', 399.99, 1, TRUE, NOW(), NOW()),
(8, 'Rechargeable Clip-On Desk Fan', 'Beat the heat wherever you are with our Rechargeable Clip-On Desk Fan! Designed for ultimate portability, this fan clips easily to your desk, bed, or any surface, delivering a refreshing breeze exactly where you need it. Enjoy adjustable speed settings and whisper-quiet operation, making it perfect for work, study, or relaxation. The built-in rechargeable battery ensures hours of cooling comfort, while the compact design fits seamlessly into any space. Stay cool, comfortable, and productive—no matter the season or setting.', 239.99, 1, TRUE, NOW(), NOW()),
(9, 'Monitor PC Lanix LX215 21.5 Pulg', 'Transform your workspace with the Lanix LX215 21.5-inch Monitor! Enjoy crisp, vibrant visuals whether you''re working, studying, or streaming your favorite content. The slim bezel and modern design make it a stylish addition to any desk, while the full HD resolution ensures every detail pops. Easy to set up and compatible with a wide range of devices, this monitor is perfect for boosting productivity and entertainment alike. Upgrade your view and experience clarity like never before.', 189.99, 1, TRUE, NOW(), NOW()),
(10, 'Samsung Galaxy Book3 Pro Intel Core i7', 'Unleash your productivity with the Samsung Galaxy Book3 Pro, powered by an Intel Core i7 processor! This ultra-slim laptop combines powerful performance with a stunning display, making it ideal for professionals, students, and creators on the go. Enjoy lightning-fast multitasking, immersive visuals, and all-day battery life in a sleek, portable package. Whether you''re editing, streaming, or working remotely, the Galaxy Book3 Pro keeps you ahead of the curve. Experience the perfect blend of style, speed, and versatility—wherever your day takes you.', 2499.99, 1, TRUE, NOW(), NOW()),
(11, 'Google Home Mini 2nd Generation-Chalk', 'Make your home smarter and your life easier with the Google Home Mini (2nd Gen) in Chalk! Control your smart devices, play your favorite music, and get answers to your questions—all with simple voice commands. The compact, stylish design fits perfectly in any room, while the powerful speaker fills your space with rich sound. Set reminders, check the weather, and enjoy hands-free help from Google Assistant, day or night. Bring convenience, entertainment, and intelligence to your home with just your voice.', 1449.99, 1, TRUE, NOW(), NOW()),
(12, 'Sony WH-1000XM4 Wired Over-Ear Noise-Cancelling', 'Immerse yourself in pure audio bliss with the Sony WH-1000XM4 Wired Over-Ear Noise-Cancelling Headphones! Experience industry-leading noise cancellation that lets you focus on your music, podcasts, or calls—no distractions, just sound. Enjoy a comfortable, ergonomic fit for hours of listening, and discover rich, detailed audio with every note. Perfect for travel, work, or relaxation, these headphones are your ticket to a world of uninterrupted sound. Upgrade your listening experience and hear what you''ve been missing.', 109.99, 1, TRUE, NOW(), NOW()),
(13, 'Custom Bluetooth Mouse', 'Enhance your workflow with our Custom Bluetooth Mouse—where style meets precision! Enjoy smooth, responsive tracking and customizable buttons that adapt to your unique needs, whether you''re working or gaming. The ergonomic design fits comfortably in your hand, reducing fatigue during long sessions. Connect wirelessly to your laptop, tablet, or desktop for seamless control and freedom of movement. Make every click count with a mouse that''s as unique as you are.', 329.99, 1, TRUE, NOW(), NOW()),
(14, 'Digital Pen - Bluetooth Technology', 'Unleash your creativity with our Digital Pen featuring advanced Bluetooth Technology! Write, draw, and interact with your devices effortlessly—perfect for artists, students, and professionals alike. Enjoy precise, lag-free input on tablets and smartphones, making note-taking and sketching a breeze. The sleek, comfortable design ensures hours of use without strain, while Bluetooth connectivity keeps you wire-free. Transform your ideas into reality with a pen that keeps up with your imagination.', 1249.99, 1, TRUE, NOW(), NOW()),
(15, 'Portable and Compact Wireless Keyboard', 'Type comfortably anywhere with our Portable and Compact Wireless Keyboard! Lightweight and slim, it fits easily into your bag or backpack, making it perfect for travel, work, or study on the go. Enjoy responsive keys and a reliable wireless connection to all your devices—laptop, tablet, or smartphone. The stylish design and long battery life mean you can work or create wherever inspiration strikes. Upgrade your typing experience and stay productive, no matter where you are.', 749.99, 1, TRUE, NOW(), NOW()),
(16, 'To be continued...', 3.1415, 1, TRUE, NOW(), NOW()),
(25, 'Ergonomic Office Chair', 'Work in comfort and style with our Ergonomic Office Chair! Designed to support your posture and reduce fatigue during long hours at your desk. Adjustable height, lumbar support, and breathable mesh back keep you cool and comfortable. Smooth-rolling wheels and a sturdy base make it easy to move around your workspace. Upgrade your office with a chair that puts your well-being first.', 1399.99, 2, TRUE, NOW(), NOW()),
(26, 'Standing Desk Converter', 'Transform your workspace with our Standing Desk Converter! Easily switch between sitting and standing to boost your energy and productivity. Spacious surface fits your monitor, laptop, and accessories. Sturdy, adjustable design ensures stability at any height. Make your workday healthier and more dynamic.', 1499.99, 2, TRUE, NOW(), NOW()),
(27, 'Wireless Keyboard & Mouse Combo', 'Streamline your workflow with our Wireless Keyboard & Mouse Combo! Enjoy reliable wireless connectivity and responsive performance for both typing and navigation. Ergonomic design reduces strain during long sessions. Perfect for home offices, students, and professionals on the go. Upgrade your setup with a combo that delivers convenience and comfort.', 699.99, 2, TRUE, NOW(), NOW()),
(28, 'Noise-Cancelling Headphones', 'Focus on your work with our Noise-Cancelling Headphones! Block out distractions and immerse yourself in music, calls, or podcasts. Comfortable, over-ear design for all-day wear. Long battery life and crystal-clear sound quality. Ideal for busy offices, travel, or study sessions.', 799.99, 2, TRUE, NOW(), NOW()),
(29, 'Bose Noise-Cancelling Earbuds ''quietcomfort''', 'Experience premium sound with Bose Noise-Cancelling Earbuds ''quietcomfort''! Advanced noise cancellation lets you focus on what matters most. Compact, comfortable fit for all-day use. Perfect for calls, music, and productivity on the move. Enjoy legendary Bose quality in a portable package.', 699.99, 2, TRUE, NOW(), NOW()),
(30, 'Desk Lamp with Adjustable Brightness', 'Illuminate your workspace with our Desk Lamp featuring Adjustable Brightness! Choose the perfect lighting for reading, writing, or computer work. Sleek, modern design fits any desk or office décor. Energy-efficient LED technology saves power and lasts longer. Brighten your day and boost your productivity.', 499.99, 2, TRUE, NOW(), NOW()),
(31, 'Monitor Stand with Storage', 'Organize your desk and improve ergonomics with our Monitor Stand with Storage! Raises your monitor to eye level, reducing neck and eye strain. Built-in compartments keep pens, notes, and accessories within reach. Sturdy construction supports most monitors and laptops. Declutter your workspace and work more comfortably.', 399.99, 2, TRUE, NOW(), NOW()),
(32, 'High-Quality Ballpoint Pen Set', 'Write smoothly and confidently with our High-Quality Ballpoint Pen Set! Includes multiple pens with comfortable grips and long-lasting ink. Perfect for note-taking, journaling, or signing important documents. Sleek design makes them a stylish addition to any desk. Enjoy effortless writing every time.', 299.99, 2, TRUE, NOW(), NOW()),
(33, 'Fountain Pen with Ink Cartridges', 'Elevate your writing with our Fountain Pen and Ink Cartridges! Smooth, elegant lines for signatures, letters, or creative work. Includes extra cartridges for long-lasting use. Ergonomic grip and balanced weight for comfortable writing. A perfect gift for students, professionals, or pen enthusiasts.', 399.99, 2, TRUE, NOW(), NOW()),
(34, 'Gel Pen Assortment', 'Add color and creativity to your notes with our Gel Pen Assortment! Smooth, vibrant ink in a variety of colors. Perfect for planners, journals, or artistic projects. Comfortable to hold and quick-drying to prevent smudges. Make every page pop with personality.', 199.99, 2, TRUE, NOW(), NOW()),
(35, 'Mechanical Pencil Set with Lead Refills', 'Write and sketch with precision using our Mechanical Pencil Set with Lead Refills! Includes multiple pencils and plenty of extra lead. Ideal for students, artists, and professionals. Comfortable grip and consistent line quality. Never run out of sharp, clean writing tools.', 139.99, 2, TRUE, NOW(), NOW()),

